### ISSUE TITLE
Modification in Algorithms

### ISSUE THREAD

**Issue by dkal3** [MengeCrowdSim/MengeUnity#12]
Hi,
I have ingrated Menge with Unity as you had shown. Now, if I would like to make some trial modifications, independently  if I use "pedvo" or "orca", how I can make it from the SimController.cs?

For example, if demo is 4square and I would like agents to follow the path they have, but don't touch the 4 obstacles.I have to change something in PedVO or ORCA files, is it right? But if I make this change nothing different is happening when I play the demo. How I can change something in PedVO or ORCA files and this change can appear in Unity, so we can see it.
Thank you in advance!!!!!!!

**Comment by curds01** [comment]
I'm not entirely clear on what you're trying to achieve. So, I'm going to make some vague suggestions and we can iterate on the final solution.

1. Your question *sounds* like you're asking about modifying the Menge code. If so, you modify the code, build it, and replace the Menge libraries in the Unity project with the new files. This is a big endeavor and is *probably* not what you want.
2. If you're actually trying to change the behavior of the agents, you'd want to play with the simulation set up. Currently, Menge (and the unity bindings) are optimized toward writing the input XML files to the simulation. If you wanted to do that dynamically, you could write XML in a .cs file and then feed it into the simulator.

**Comment by dkal3** [comment]
Thank you for your answer!!!
Actually, I would like to change PedVO or ORCA algorithm, and see the results in Unity.
 Lets say I modify PedVO algorithm. 
1) Specifically, I would like to change the computeNewVelocity() from PedVOAgent.cpp. I have to change it, built it and replace the Menge libraries in the Unity project with the new files? Or there is a way from the SimController.cs?
2) If I want simply, agents follow their path, but when they find an obstacle, just keep 10cm distance from it and not touch them. How I could do that?

**Comment by curds01** [comment]
1. The C# bindings are such, that you'll have to modify everything in C++ and replace the libraries. Sorry about that.
2. To create a 10 cm buffer you have several options:
    1. Simulate the agents 10cm larger than you visualize them. That will also make it so that the agents don't get as close (by 20 cm -- 10 from each agent). 
    2. Modify the simulation obstacles vs the visualization obstacles a similar way -- offset them all by 10 cm.
    3. Introduce a "clearance" parameter into a pedestrian model that uses that value to explicitly modify its relationship with obstacles only. This can be tricky -- is this a *hard* limit or a *soft* limit? What happens if they get really dense? Can they get closer to the obstacles. Do you add it to all agents (probably not) or just a specific pedestrian model?

**Comment by dkal3** [comment]
Thank you so much for your detailed answer!!!
For question (2), I tried your second answer (ii) and the result is this that I expected.
Have a nice day!!!

**Comment by curds01** [comment]
Glad to know it helped. I'm going to close this issue for now; if you feel this isn't resolved, we can re-open it.

**Comment by dkal3** [comment]
ok no problem!!You can close this issue!

**Comment by dkal3** [comment]
Hi!!!
I would like to re-open this issue! I am facing a problem! 
As i have mentioned , I want to modify Menge code. Specifically, in  Menge\src\Menge\MengeCore\Agents\BaseAgent.cpp. 
I want to modify only the initial values of some variables and see what is happening in Unity, Unfortunately, I can not see any modification.
 You told me to modify the code, built Menge and replace the Menge libraries in the Unity project with the new files.
Below is what I do:
-Modify the code
-Built Menge two times (one for 32-bit and one for 64-bit).
-I expect a file with the name "MengeCore.dll". 
-Go to MengeUnity\Assets\Plugins\x86 and put inside the MengeCore.dll from 32-bit built.
-Go to MengeUnity\Assets\Plugins\x86_64 and put inside the MengeCore.dll from 64-bit built.
-I have the same name MengeCore.dll in the different files x86 and x86_64.
-In MengeUnity\Assets\Scripts I have put the MengeCS.dll from the execution of MengeCS.

I would be appreciate if you could help me!

**Comment by curds01** [comment]
I don't know that I'll be of much help. My interaction with Unity is limited. I was able to get it to work once, I documented it in this project in hopes that it would allow me to reproduce it in the future. If you're telling me that it doesn't work, I'm not in a good position to help out. The Unity support was a bit of a stretch and an afterthought.

I'll see if I can't get around to trying to update the Menge plugin locally by following the instructions. Maybe I have an error I can figure out.

**Comment by dkal3** [comment]
Ok! Thank you! One clarification! When we talk about Menge libraries we refer to .dll files right?
Except Unity,I tried to see if modifications in the code, appear in Menge.
That is, I modify the code (specifically speed set it to 0.1 from 1.34 that was initially), built it and with the command
 -m pedvo -p ..\examples\core\4square.xml 
I hope that I will see some difference. 
From 4SquareS.xml that speed again initializes, I have deleted it. 
Is it something that I do not think and do right?
Thank you in advance from your time!

**Comment by curds01** [comment]
Let me see if I understood properly.

Your goal is to make some modifications to Menge and have them be available in Unity.
You made a small change (to test the idea) -- "setting the speed to 0.1 from 1.34". You want to confirm that the change had an affect outside of Unity. So, you run the 4square.xml.

This is where I need clarification.

I *infer* that you didn't see any change in behavior from the change you made in the code. I don't know *how* you made the change, but I would *guess* you changed the [default value set in `BaseAgent.cpp`](https://github.com/MengeCrowdSim/Menge/blob/master/src/Menge/MengeCore/Agents/BaseAgent.cpp#L56).

That won't lead to any visible changes -- in the `4square.xml` demo (and all of them, in fact), the scenario specification *explicitly* defines the preferred speed such that the in-code default value will *always* get overwritten.

Let me know if my understanding and inferences are correct.

**Comment by dkal3** [comment]
Yes excactly, I change the default value set in BaseAgent,cpp. 
With scenario specification you mean the 4spuare.xml files? 
I have changed also the 4squareS.xml by deleting from the line 15-16 the preffered and max speed:
<AgentProfile name="group1" >
		<Common max_angle_vel="360"  max_neighbors="10" obstacleSet="1" neighbor_dist="15" pref_speed="1.34" r="0.2" max_speed="2" max_accel="5" />
I make these changes, build Menge and now have the new Exe file and run the command I mentioned
(-m pedvo -p ..\examples\core\4square.xml). 
What do I have to change, so to see modification.

**Comment by dkal3** [comment]
Yes excactly, I change the default value set in BaseAgent,cpp.
With scenario specification you mean the 4spuare.xml files?
I have changed also the 4squareS.xml by deleting from the line 15-16 the preffered and max speed:

<AgentProfile name="group1" >
		<Common max_angle_vel="360"  max_neighbors="10" obstacleSet="1" neighbor_dist="15" pref_speed="1.34" r="0.2" max_speed="2" max_accel="5" />

I make these changes, build Menge and now have the new Exe file and run the command I mentioned
(-m pedvo -p ..\examples\core\4square.xml).
What do I have to change, so to see modification.

**Comment by dkal3** [comment]
Yes excactly, I change the default value set in BaseAgent,cpp.
With scenario specification you mean the 4spuare.xml files?
I have changed also the 4squareS.xml by deleting from the line 15-16 the preffered speed.

I make these changes, build Menge and now have the new Exe file and run the command I mentioned
(-m pedvo -p ..\examples\core\4square.xml).
What do I have to change, so to see modification.

**Comment by curds01** [comment]
So, to do that, try changing [this line](https://github.com/MengeCrowdSim/Menge/blob/master/src/Menge/MengeCore/Agents/AgentInitializer.cpp#L60).

**Comment by dkal3** [comment]
Thank you, thank you, thank you!!!
I was the one who made the mistake and did not make all the appropriate changes in the code.
Τhe process is what you have mentioned. I can see now the modifications and in the Unity project!
Thank you a lot!!!!

**Comment by curds01** [comment]
No problem. I'm going to go ahead and close the issue again.
