### ISSUE TITLE
How permissive is the license?

### ISSUE THREAD

**Issue by Xerios** [MengeCrowdSim/MengeUnity#2]
First of all, love the fact that this was actually ported to Unity! Kudos for that
I remember reading the papers few years back while trying really poorly to recreate it in C#.

Anyhow, I don't find the license that clear. Is it possible to use this library for commercial indie game development ?

**Comment by MengeCrowdSim** [comment]
Here's the short answer.  We've had a discussion today and have decided to simply release Menge and associated work under a full open-source license.  In the next week or so, we'll update the projects to reflect this.  In the short-term, you can proceed as if you had _carte blanche_.  

You can expect the license to have the standard attribution clauses (e.g., you can't take credit for our work and you should have our logo somewhere giving credit.)

**Comment by Xerios** [comment]
Thanks for the quick answer !

**Comment by MengeCrowdSim** [comment]
License for Menge changed in: https://github.com/MengeCrowdSim/Menge/pull/46

It is now a wide open license. Go crazy.
