### ISSUE TITLE
SimController.cs: The variable `result' is assigned but its value is never used

### ISSUE THREAD

**Issue by 321abhay** [MengeCrowdSim/MengeUnity#9]
Hi,

I am getting following warning from unity.

Assets/Scripts/SimController.cs(35,8): warning CS0219: The variable `result' is assigned but its value is never used

**Comment by MengeCrowdSim** [comment]
That is correct.

1) It doesn't affect the functioning of the code; it is only a warning.
2) If you pull master and rebase on it, that warning will go away.
